-- AlterTable
ALTER TABLE "ProductionPlan" ADD COLUMN IF NOT EXISTS "supervisor" TEXT NOT NULL DEFAULT '';
ALTER TABLE "ProductionPlan" ADD COLUMN IF NOT EXISTS "drawingNo" TEXT NOT NULL DEFAULT '';
ALTER TABLE "ProductionPlan" ADD COLUMN IF NOT EXISTS "formulaNo" TEXT NOT NULL DEFAULT '';
ALTER TABLE "ProductionPlan" ADD COLUMN IF NOT EXISTS "moldNo" TEXT NOT NULL DEFAULT '';
ALTER TABLE "ProductionPlan" ADD COLUMN IF NOT EXISTS "productName" TEXT NOT NULL DEFAULT '';
